### ISSUE TITLE
Have you thought of adding bot feature

### ISSUE THREAD

**Issue by krakenwizard10-ai** [Harry-kp/Chegg_autoskip_question#1]
Thinking of implementing bot feature like auto pause on questions that are asked from specific domain, and inform as phone notification that new easy question available, How does it sound like, more advance feature like auto adding template answer, Have you thought anything like this?

**Comment by Harry-kp** [comment]
First of all a  big thank you for showing your interest in this project . I admire your valuable suggestions.
Yes . I thought of these amazing features and tried to implement them using selenium .  I am working on that  .It will take time . So I created this script to fill the space till then .

**Comment by krakenwizard10-ai** [comment]
Javascript better option than python, selenium does not work for this site well.
