### ISSUE TITLE
Those requirements not matching your script

### ISSUE THREAD

**Issue by krakenwizard10-ai** [Harry-kp/Chegg_autoskip_question#2]
remove unnecessary requirement you mention in text file, you wrote very terrible script, it does not work as expected.

**Comment by Harry-kp** [comment]
Yes , I got that mistake .It was a silly one.  I was using conda virtual environment that is why it is showing unnecessary modules.
I updated that requirements.txt file and now it contains only the required modules.
Pls elaborate or add some screenshots or output of the script so that I can understand why it doesn't work up to your expectations.

**Comment by krakenwizard10-ai** [comment]
First skip button does not get clicked, last two works but redirects to home page. **after aligning button coordinates according to my display.** used right click button paste on answering window, question got skipped, after complete answer written, question got skipped, these small details you must check. Hope you will improve them in future, you must check there is one available chrome extension to skip question, I am also working on it, will try to contribute to your script after that.
https://github.com/Harry-kp/Chegg_autoskip_question/blob/2690b99d2baee817ef5289bbac97f3298d86c518/autoskip_chegg_question.py#L9

**Comment by Harry-kp** [comment]
Yes.. that right click vulnerability is a matter of concern . I myself got stuck in a situation where I wrote the whole answer and when i try to paste it using right click the question got skipped . For now , I can say that :-

- Use Ctrl + V to paste 

- **If possible , stop the script in terminal using Ctrl + Z when you find a question to answer**

- Be more cautious while using mouse buttons to prevent script from skipping good question.

I know the above methods are temporary solution and not a good idea to tackle a problem . They are just quick fixes. 
I will roll out a permanent solution soon .
